# Site
repository: Resdigit/resume-cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Renato Marchio
title: Cloud Engineer
email: renatomarchio@gmail.com
website: www.github.com/resdigit

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: https://www.linkedin.com/in/renatomarchio/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  An experienced professional, with a passion for new technology and 3D. After several years of doing 3D visualisation, I have recently expanded my technological skillset to include cloud technology, focussing on Cloud Solutions.

#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: |
          Project Management * Technical Understanding * Good Under Pressure * Attention to Detail * Problem Solving * 3D Architectural Visualisation * Post Production * Animation  
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ARKO
        # link: boringcompany.com
        link_text: London
        sub_title: Senior 3D Visualiser
        caption: Feb 2020 - Sept 2021
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Co-ordinated teams to create visuals of large-scale developments.
          * Established rendering farm on AWS using spot instances.
          * Setup AWS Thinkbox Deadline to manage a render queue.
          * Did day-to-day IT on render farm servers, installing/ updating software, fixing issues.
          * Improved library assets searchability by using metadata tags.
          * Used various techniques to improve render times thereby reducing costs.
          * Used Jira for project management.
          * Regularly posted tech tips on Slack to keep staff up to date with the latest trends.
      - layout: left
        title: RESOLUTION DIGITAL LTD
        # link: boringcompany.com
        link_text: London
        sub_title: 3D Visualiser
        caption: Oct 2003 - Feb 2020
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Director of Resolution Digital Ltd for 17 years. 
          * Liaised directly with clients to create 3D visuals.
          * Created project budgets. 
          * Refined production techniques to create fast and accurate images on time and under budget.
          * Regularly looked into integrating new techniques/software to improve delivery. 
          * Wrote small python scripts to improve 3D workflows. 
          * Created a website using WordPress. 
      - layout: left
        title: CONCISE GROUP
        # link: boringcompany.com
        link_text: London
        sub_title: multimedia and video services
        caption: Mar 2002 - Oct 2003
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Created 3D elements for large format graphics presentations.
          * Looked at ways to get smooth playback of video files.
          * Setup MOCAP system for realtime facial animated characters.
      - layout: left
        title: DIGITAL VIDEO FACILITIES
        # link: boringcompany.com
        link_text: Johannesburg, SA
        sub_title: Lead 3D Animator
        caption: Oct 2000 - Feb 2002
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
          * Head of Graphics.
          * PC and Mac integration.
          * Helped transform the company from analog to digital.
          * Reported directly to Senior management.
          * Created and pitched proposals to clients.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Certified Solutions Architect - Associate
        caption: 2022 - 2025
        sub_title: AWS
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          
      - layout: top-middle
        title: Certified Cloud Practitioner
        caption: 2021 - 2024
        sub_title: AWS
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.
           

      - layout: top-middle
        title: Baccalaureus Technologiae Architectural Technology (Technology)
        caption: 1993 - 1996
        sub_title: Technikon Witwatersrand
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rugby
      - Cub Scout Leader
      - 3D visualisation
            
      Visuals I created  
        ![porfolio](https://raw.github.com/Resdigit/modern-resume-theme/gh-pages/images/Portfolio.jpg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme


sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  "README.md",
  "*.sh"
]
